/**
 * Unit tests for `ruleGiftDeclaredVsDenied` (LSAG B — Batch B).
 *
 * Pure-function tests covering the emit and omit paths. No DB, no mocks.
 * See plan in `.lovable/plan.md` (Batch B test matrix).
 */

import { describe, it, expect } from 'vitest';
import {
  ruleGiftDeclaredVsDenied,
  type GiftDeclarationInputs,
  type GiftDeclarationTransactionInput,
} from '../exceptionEngine';

let _idCounter = 0;
function tx(
  overrides: Partial<GiftDeclarationTransactionInput> = {},
): GiftDeclarationTransactionInput {
  _idCounter += 1;
  return {
    id: overrides.id ?? `tx-${_idCounter}`,
    direction: overrides.direction ?? 'incoming',
    amount: overrides.amount ?? 1000,
    description: overrides.description ?? null,
    tx_date: overrides.tx_date ?? null,
    classifiedCategory: overrides.classifiedCategory ?? null,
  };
}

function inputs(
  overrides: Partial<GiftDeclarationInputs> = {},
): GiftDeclarationInputs {
  return {
    giftDeclared: 'giftDeclared' in overrides ? overrides.giftDeclared : false,
    transactions: overrides.transactions ?? [],
  };
}

describe('ruleGiftDeclaredVsDenied', () => {
  // ── Emit paths ──────────────────────────────────────────────────

  it('emits when gift_declared = false and one transaction is classified as gift', () => {
    const t = tx({ id: 'gift-1', amount: 5000, classifiedCategory: 'gift', description: 'transfer' });
    const result = ruleGiftDeclaredVsDenied(inputs({ transactions: [t] }));
    expect(result).toHaveLength(1);
    expect(result[0].exceptionType).toBe('gift_declared_vs_denied');
    expect(result[0].severity).toBe('high');
    expect(result[0].linkedRefId).toBe('gift-1');
    expect(result[0].linkedRefTable).toBe('sow_transactions');
    expect(result[0].canTriggerEnquiry).toBe(true);
    expect(result[0].reviewerConfirmationRequired).toBe(true);
    expect(result[0].suggestedNextAction).toMatch(/gift letter/i);
  });

  it('emits when gift_declared = false and ≥ 2 token-match transactions are present', () => {
    const t1 = tx({ id: 't1', amount: 1500, description: 'From Mum' });
    const t2 = tx({ id: 't2', amount: 800, description: 'Birthday gift' });
    const result = ruleGiftDeclaredVsDenied(inputs({ transactions: [t1, t2] }));
    expect(result).toHaveLength(1);
    expect(result[0].linkedRefId).toBe('t1');
    expect(result[0].rationale).toMatch(/From Mum/);
    expect(result[0].rationale).toMatch(/Birthday gift/);
    expect(result[0].quantitativeBasis).toMatch(/Cited transactions: 2/);
  });

  it('emits with a single classified gift transaction even when no token hits exist', () => {
    const t = tx({ id: 'g1', amount: 10_000, classifiedCategory: 'gift', description: 'unrelated narrative' });
    const result = ruleGiftDeclaredVsDenied(inputs({ transactions: [t] }));
    expect(result).toHaveLength(1);
    expect(result[0].linkedRefId).toBe('g1');
  });

  it('treats token matches as case-insensitive ("FROM MUM", "birthday GIFT")', () => {
    const t1 = tx({ id: 'a', description: 'FROM MUM' });
    const t2 = tx({ id: 'b', description: 'birthday GIFT' });
    const result = ruleGiftDeclaredVsDenied(inputs({ transactions: [t1, t2] }));
    expect(result).toHaveLength(1);
  });

  it('produces a stable LSAG-B-aligned exception shape (severity high, sow_transactions ref, contradiction action)', () => {
    const t = tx({ id: 'shape', amount: 2500, classifiedCategory: 'gift' });
    const result = ruleGiftDeclaredVsDenied(inputs({ transactions: [t] }));
    expect(result[0]).toMatchObject({
      exceptionType: 'gift_declared_vs_denied',
      severity: 'high',
      linkedRefTable: 'sow_transactions',
      linkedField: 'classified_category',
      autoGenerated: true,
      reviewerConfirmationRequired: true,
      canTriggerEnquiry: true,
    });
  });

  // ── Omit paths ──────────────────────────────────────────────────

  it('does NOT emit when gift_declared = false but only one token-match tx (corroboration threshold not met)', () => {
    const t = tx({ id: 'lonely', description: 'Birthday gift' });
    const result = ruleGiftDeclaredVsDenied(inputs({ transactions: [t] }));
    expect(result).toEqual([]);
  });

  it('does NOT emit when gift_declared = true even with classified gift transactions', () => {
    const t = tx({ id: 'declared', classifiedCategory: 'gift', description: 'From Dad' });
    const result = ruleGiftDeclaredVsDenied(
      inputs({ giftDeclared: true, transactions: [t] }),
    );
    expect(result).toEqual([]);
  });

  it('does NOT emit when gift_declared is null / undefined (absence ≠ denial)', () => {
    const t = tx({ classifiedCategory: 'gift' });
    expect(
      ruleGiftDeclaredVsDenied(inputs({ giftDeclared: null, transactions: [t] })),
    ).toEqual([]);
    expect(
      ruleGiftDeclaredVsDenied(inputs({ giftDeclared: undefined, transactions: [t] })),
    ).toEqual([]);
    expect(ruleGiftDeclaredVsDenied(undefined)).toEqual([]);
  });

  it('does NOT emit when gift_declared = false but there are no incoming transactions', () => {
    expect(ruleGiftDeclaredVsDenied(inputs({ transactions: [] }))).toEqual([]);
  });

  it('does NOT emit on outgoing transactions even if their description contains gift tokens', () => {
    const t1 = tx({ id: 'o1', direction: 'outgoing', description: 'Birthday gift for Mum' });
    const t2 = tx({ id: 'o2', direction: 'outgoing', description: 'gift to dad', classifiedCategory: 'gift' });
    const result = ruleGiftDeclaredVsDenied(inputs({ transactions: [t1, t2] }));
    expect(result).toEqual([]);
  });

  it('does NOT count substring-only matches such as "giftcard purchase" (word-boundary enforced)', () => {
    const t1 = tx({ id: 'gc1', description: 'Giftcard purchase' });
    const t2 = tx({ id: 'gc2', description: 'Argos giftcards' });
    const result = ruleGiftDeclaredVsDenied(inputs({ transactions: [t1, t2] }));
    expect(result).toEqual([]);
  });

  it('does NOT trip on "Christmas drinks" + "Birthday present" (excluded bare tokens)', () => {
    const t1 = tx({ id: 'x1', description: 'Christmas drinks' });
    const t2 = tx({ id: 'x2', description: 'Birthday present' });
    const result = ruleGiftDeclaredVsDenied(inputs({ transactions: [t1, t2] }));
    expect(result).toEqual([]);
  });

  // ── Defensive paths ─────────────────────────────────────────────

  it('handles missing description / amount gracefully', () => {
    const t1 = tx({ id: 'n1', amount: null, description: null, classifiedCategory: 'gift' });
    const result = ruleGiftDeclaredVsDenied(inputs({ transactions: [t1] }));
    expect(result).toHaveLength(1);
    expect(result[0].quantitativeBasis).toContain('Cited transactions: 1');
  });

  // ── Word-boundary token regression ──────────────────────────────
  describe('word-boundary token regression', () => {
    it('B-W1: does NOT emit on "giftcard" / "giftset" (gift not a standalone token)', () => {
      const t1 = tx({ id: 'b1', description: 'giftcard' });
      const t2 = tx({ id: 'b2', description: 'giftset' });
      expect(
        ruleGiftDeclaredVsDenied(inputs({ transactions: [t1, t2] })),
      ).toEqual([]);
    });

    it('B-W2: does NOT emit on "mummy" / "daddy" (mum/dad not standalone)', () => {
      const t1 = tx({ id: 'b3', description: 'mummy' });
      const t2 = tx({ id: 'b4', description: 'daddy' });
      expect(
        ruleGiftDeclaredVsDenied(inputs({ transactions: [t1, t2] })),
      ).toEqual([]);
    });

    it('B-W3: emits on "mum," and "dad." (punctuation is a word boundary)', () => {
      const t1 = tx({ id: 'b5', description: 'mum,' });
      const t2 = tx({ id: 'b6', description: 'dad.' });
      const result = ruleGiftDeclaredVsDenied(inputs({ transactions: [t1, t2] }));
      expect(result).toHaveLength(1);
    });

    it('B-W4: does NOT emit on a single transaction even if multiple gift tokens appear', () => {
      const t = tx({ id: 'b7', description: 'GIFT FROM MUM' });
      expect(ruleGiftDeclaredVsDenied(inputs({ transactions: [t] }))).toEqual([]);
    });

    it('B-W5: emits on "  birthday  " and "\\tfrom parents\\n" (whitespace boundary)', () => {
      const t1 = tx({ id: 'b8', description: '  birthday  ' });
      const t2 = tx({ id: 'b9', description: '\tfrom parents\n' });
      const result = ruleGiftDeclaredVsDenied(inputs({ transactions: [t1, t2] }));
      expect(result).toHaveLength(1);
    });

    it('B-W6: does NOT emit when descriptions are null / empty string', () => {
      const t1 = tx({ id: 'b10', description: null });
      const t2 = tx({ id: 'b11', description: '' });
      expect(
        ruleGiftDeclaredVsDenied(inputs({ transactions: [t1, t2] })),
      ).toEqual([]);
    });
  });
});
