import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import PublicNav from "@/components/PublicNav";

const TermsAndConditions = () => {
  return (
    <div className="min-h-screen bg-background">
      <PublicNav />
      <div className="max-w-4xl mx-auto px-6 py-12 pt-24">
        <Button asChild variant="ghost" size="sm" className="mb-6 text-muted-foreground hover:text-foreground">
          <Link to="/">
            <ArrowLeft size={16} className="mr-2" /> Back
          </Link>
        </Button>

        <h1 className="text-3xl font-bold text-foreground mb-2">Terms and Conditions of Use</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: 28 February 2026</p>

        <div className="prose prose-sm max-w-none text-foreground space-y-6">
          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">1. Definitions</h2>
            <p className="text-muted-foreground leading-relaxed">
              "Olimey AI" refers to the AI-powered legal technology platform operated by Olimey AI ("the Company", "we", "us", "our"). "User", "you", or "your" refers to any individual or entity accessing or using the Platform. "AI Outputs" means any text, reports, risk assessments, draft correspondence, analysis, or other content generated by the Platform's artificial intelligence systems. "Professional User" means a qualified legal professional, solicitor, licensed conveyancer, or other regulated individual using the Platform in the course of their professional duties.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">2. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By registering for, accessing, or using Olimey AI, you confirm that you have read, understood, and agree to be bound by these Terms and Conditions. If you do not agree, you must not use the Platform. These Terms constitute a legally binding agreement between you and the Company. Use of the Platform is also subject to our Privacy Policy and AI Usage Disclaimer, which are incorporated by reference.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">3. Nature of the Service — AI as a Professional Support Tool</h2>
            <p className="text-muted-foreground leading-relaxed">
              Olimey AI is designed exclusively as a professional assistance tool for qualified legal professionals. The Platform uses artificial intelligence to analyse property search documents, generate risk assessments, and draft correspondence. <strong className="text-foreground">AI Outputs do not constitute legal advice.</strong> They are provided to assist — not replace — the independent professional judgement of a qualified legal practitioner.
            </p>
            <p className="text-muted-foreground leading-relaxed mt-2">
              You acknowledge and agree that:
            </p>
            <ul className="list-disc pl-6 text-muted-foreground space-y-1.5 mt-2">
              <li>AI Outputs are generated by machine learning models and may contain errors, omissions, or inaccuracies.</li>
              <li>You are solely responsible for reviewing, verifying, and approving all AI Outputs before relying upon, actioning, or communicating them to any client, lender, insurer, or third party.</li>
              <li>The Platform does not and cannot replace the professional obligations, regulatory duties, or standard of care required of a qualified legal practitioner.</li>
              <li>No solicitor-client, advisory, or fiduciary relationship is created between you and the Company by virtue of your use of the Platform.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">4. User Obligations and Professional Responsibility</h2>
            <p className="text-muted-foreground leading-relaxed">
              As a Professional User, you warrant and represent that:
            </p>
            <ul className="list-disc pl-6 text-muted-foreground space-y-1.5 mt-2">
              <li>You are a qualified legal professional authorised to practise in the relevant jurisdiction.</li>
              <li>You will exercise independent legal judgement in all matters and will not delegate your professional responsibilities to the Platform.</li>
              <li>You will comply with all applicable laws, regulations, and professional conduct rules, including those of the Solicitors Regulation Authority (SRA), the Council for Licensed Conveyancers (CLC), or any other applicable regulatory body.</li>
              <li>You will not use the Platform for any unlawful purpose or in any manner that could damage, disable, or impair the service.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials and for all activities conducted under your account.</li>
              <li>You will ensure that any data uploaded to the Platform is done so in compliance with your professional and regulatory obligations, including data protection legislation.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">5. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law:
            </p>
            <ul className="list-disc pl-6 text-muted-foreground space-y-1.5 mt-2">
              <li>The Company shall not be liable for any loss, damage, claim, or expense arising from your reliance on AI Outputs without independent verification.</li>
              <li>The Company makes no warranty, express or implied, regarding the accuracy, completeness, reliability, or fitness for purpose of any AI Output.</li>
              <li>The Company's total aggregate liability in connection with these Terms shall not exceed the fees paid by you in the twelve (12) months preceding the event giving rise to the claim.</li>
              <li>In no event shall the Company be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, goodwill, or professional reputation.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">6. Indemnification</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree to indemnify, defend, and hold harmless the Company, its directors, officers, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or in any way connected with: (a) your use of the Platform; (b) your reliance on AI Outputs without independent professional review; (c) your breach of these Terms; or (d) your violation of any applicable law, regulation, or professional conduct rule.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">7. Audit Trail and Record Keeping</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Platform maintains a comprehensive audit trail of all user activities, AI analyses, and system interactions for regulatory compliance and professional indemnity defence purposes. This includes, but is not limited to:
            </p>
            <ul className="list-disc pl-6 text-muted-foreground space-y-1.5 mt-2">
              <li>Timestamps of user registrations, logins, and AI disclaimer acknowledgements.</li>
              <li>Records of document uploads, AI review requests, and report generation.</li>
              <li>User modifications to AI-generated content.</li>
              <li>Feedback submissions and quality assurance results.</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-2">
              You consent to the creation and retention of these records. Audit records are immutable and cannot be altered or deleted.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">8. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              All intellectual property rights in the Platform, including its software, algorithms, user interface, and documentation, are and shall remain the exclusive property of the Company. You retain ownership of any documents and data you upload to the Platform. You grant the Company a limited, non-exclusive licence to process such data solely for the purpose of providing the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">9. Data Protection and Privacy</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Company processes personal data in accordance with the UK General Data Protection Regulation (UK GDPR) and the Data Protection Act 2018. Client data uploaded to the Platform is processed solely for the purpose of providing the service and is not used for AI model training. The Platform is designed to maintain ISO 27001:2022, SOC 2 Type II, and GDPR compliance standards.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">10. Account Suspension and Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Company reserves the right to suspend or terminate your account at any time if you breach these Terms, engage in conduct that may expose the Company to liability, or for any other reason at the Company's sole discretion. Upon termination, your right to access the Platform shall cease immediately, though audit records will be retained in accordance with our data retention policies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">11. Modifications to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Company reserves the right to modify these Terms at any time. Material changes will be communicated to you via email or through the Platform. Continued use of the Platform after such notification constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">12. Governing Law and Jurisdiction</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of England and Wales. Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">13. Severability</h2>
            <p className="text-muted-foreground leading-relaxed">
              If any provision of these Terms is held to be invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mt-8 mb-3">14. Entire Agreement</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms, together with the AI Usage Disclaimer and{" "}
              <Link to="/privacy" className="text-accent hover:underline font-medium">Privacy Policy</Link>
              , constitute the entire agreement between you and the Company regarding your use of the Platform and supersede all prior agreements and understandings.
            </p>
          </section>

          <section className="border-t border-border pt-6 mt-8">
            <p className="text-muted-foreground text-sm">
              Olimey AI · Registered in England and Wales<br />
              For queries regarding these Terms, please contact: <span className="text-accent">legal@lexsentinel.co.uk</span>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
