import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FileText, Download } from "lucide-react";
import { toast } from "sonner";
import jsPDF from "jspdf";

const AI_TASKS = [
  "Title Review & Risk Assessment",
  "Source of Wealth Verification",
  "Draft Document Review",
  "Pre-Exchange Compliance Check",
  "Search Report Analysis",
  "AML Compliance Screening",
];

interface Props {
  caseReference: string;
  propertyAddress: string;
  clientName?: string;
}

export default function AIUsageDisclosureButton({ caseReference, propertyAddress, clientName }: Props) {
  const [open, setOpen] = useState(false);
  const [solicitorName, setSolicitorName] = useState("");
  const [sraId, setSraId] = useState("");
  const [task, setTask] = useState("");

  const handleGenerate = () => {
    if (!solicitorName.trim() || !sraId.trim() || !task) {
      toast.error("All fields are required.");
      return;
    }
    if (!/^\d{5,8}$/.test(sraId.trim())) {
      toast.error("SRA ID must be 5-8 digits.");
      return;
    }

    const doc = new jsPDF();
    const now = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
    const margin = 20;
    let y = 30;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("AI Usage Disclosure", margin, y);
    y += 10;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Date: ${now}`, margin, y);
    y += 6;
    doc.text(`Case Reference: ${caseReference}`, margin, y);
    y += 6;
    doc.text(`Property: ${propertyAddress}`, margin, y);
    y += 14;

    if (clientName) {
      doc.text(`Dear ${clientName},`, margin, y);
      y += 10;
    }

    const body = `In the processing of this matter, Olimey AI was used for ${task}. This was overseen by ${solicitorName.trim()} (SRA: ${sraId.trim()}) in accordance with the 2026 SRA Code of Conduct. No automated decision was made without human verification.`;

    const lines = doc.splitTextToSize(body, 170);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 10;

    doc.text("This disclosure is provided in accordance with:", margin, y);
    y += 6;
    doc.text("• SRA Code of Conduct 2026 — Use of AI in Legal Practice", margin, y);
    y += 5;
    doc.text("• EU AI Act Articles 13–15 — Transparency & Human Oversight", margin, y);
    y += 5;
    doc.text("• HMLR 2026 Contractual Control Regulations", margin, y);
    y += 14;

    doc.text(`Yours faithfully,`, margin, y);
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.text(solicitorName.trim(), margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.text(`SRA Number: ${sraId.trim()}`, margin, y);
    y += 12;

    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text("Generated by Olimey AI — SRA & EU AI Act Compliant — Mar 2026", margin, 285);

    doc.save(`AI_Disclosure_${caseReference}.pdf`);
    toast.success("Disclosure PDF generated.");
    setOpen(false);
  };

  return (
    <>
      <Button variant="outline" size="sm" className="gap-1.5" onClick={() => setOpen(true)}>
        <FileText size={14} />
        AI Disclosure
      </Button>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2"><FileText className="h-5 w-5 text-primary" /> Generate AI Usage Disclosure</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Generate a client-facing PDF letter disclosing AI usage on this matter, in accordance with the 2026 SRA Code of Conduct.
            </p>
            <div className="space-y-2">
              <Label>AI Task Performed *</Label>
              <Select value={task} onValueChange={setTask}>
                <SelectTrigger><SelectValue placeholder="Select task…" /></SelectTrigger>
                <SelectContent>
                  {AI_TASKS.map(t => <SelectItem key={t} value={t}>{t}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Supervising Solicitor *</Label>
              <Input value={solicitorName} onChange={e => setSolicitorName(e.target.value)} placeholder="e.g. Jane Smith" />
            </div>
            <div className="space-y-2">
              <Label>SRA ID Number *</Label>
              <Input value={sraId} onChange={e => setSraId(e.target.value)} placeholder="e.g. 123456" maxLength={8} />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button>
            <Button onClick={handleGenerate} disabled={!solicitorName.trim() || !sraId.trim() || !task}>
              <Download className="h-3.5 w-3.5 mr-1" /> Generate PDF
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
