/**
 * Armalytix Contradiction Detection Engine
 *
 * Pure-function module with typed placeholder detection rules.
 * Each function returns ContradictionResult[] for any issues found.
 *
 * The runFullAnalysis orchestrator chains all 8 analysis modules:
 * classify → triage → match → reconcile → except → enquiry → reviewer → decision.
 */

import type { ContradictionResult } from './provenanceTypes';
import { classifyAllTransactions, type RawTransaction, type ClassificationContext, type ClassifiedTransaction } from './transactionClassifier';
import { assessBulkMateriality, detectRepeatedPatterns, type MaterialityContext, type MaterialityAssessment, type RepeatedPattern, type MaterialityConfig, DEFAULT_MATERIALITY_CONFIG } from './materialityEngine';
import { matchAllTransactions, type MatchableFundSource, type MatchResult } from './transactionMatcher';
import { reconcileAllSources, buildFundingChain, type ReconciliationInputs, type SourceReconciliation, type FundingChainSummary } from './reconciliationEngine';
import { generateExceptions, buildExceptionsLedger, type ExceptionItem, type ExceptionsLedger } from './exceptionEngine';
import { generateDraftEnquiries, type DraftEnquiry } from './enquiryGenerator';
import { buildReviewerSummary, type ReviewerSummary } from './reviewerOutputBuilder';
import { buildDecisionSupport, type DecisionSupportOutput } from './decisionSupportEngine';

// ── Lightweight type stubs for detector inputs ───────────────────
// These mirror the DB row shapes; the full DB types will be used
// once the types.ts file regenerates with the new columns.

interface FundSourceRecord {
  id: string;
  case_id: string;
  source_category?: string | null;
  declared_amount?: number | null;
  date_received?: string | null;
  years_to_accumulate?: number | null;
  employer_name?: string | null;
  annual_gross_salary?: number | null;
  outside_uk?: boolean | null;
  supporting_doc_uploaded?: boolean | null;
  supporting_doc_name?: string | null;
  verification_status?: string | null;
  linked_account_ids?: string[] | null;
  income_explains_savings?: boolean | null;
  bonuses_declared?: boolean | null;
}

interface EvidenceItemRecord {
  id: string;
  ref_table: string;
  ref_id: string;
  source_origin?: string | null;
  verification_status?: string | null;
}

interface TransactionRecord {
  id: string;
  case_id: string;
  direction?: string | null;
  tx_date?: string | null;
  amount?: number | null;
  description?: string | null;
  linked_fund_source_id?: string | null;
  explanation_status?: string | null;
}

interface ManualBalanceRecord {
  id: string;
  case_id: string;
  amount?: number | null;
  attachment_name?: string | null;
  evidence_status?: string | null;
  counted_toward_proof?: boolean | null;
}

interface PartyRecord {
  id: string;
  case_id: string;
  role?: string | null;
  full_name?: string | null;
  contribution_amount?: number | null;
  buyer_relationship?: string | null;
}

interface IncomeVerificationRecord {
  id: string;
  payslip_name_match?: boolean | null;
  matched_employer_name?: string | null;
  salary_matched_to_bank?: boolean | null;
  avg_salary_credit?: number | null;
  net_pay_on_payslip?: number | null;
}

interface ConnectedAccountRecord {
  id: string;
  account_holder_name?: string | null;
  account_currency?: string | null;
}

interface ReportHeaderRecord {
  mortgage_amount?: number | null;
  mortgage_lender?: string | null;
  mortgage_offer_in_place?: boolean | null;
}

// ── Detection functions ──────────────────────────────────────────

/**
 * 1. Declared source exists but no supporting evidence linked.
 */
export function detectUnevidencedSource(
  fundSource: FundSourceRecord,
  evidenceItems: EvidenceItemRecord[]
): ContradictionResult[] {
  const linked = evidenceItems.filter(
    (e) => e.ref_table === 'sow_fund_sources' && e.ref_id === fundSource.id
  );

  if (linked.length === 0 && fundSource.declared_amount && fundSource.declared_amount > 0) {
    return [{
      type: 'unevidenced_source',
      summary: `Declared source "${fundSource.source_category ?? 'unknown'}" (£${fundSource.declared_amount}) has no linked evidence.`,
      severity: 'high',
      affectedRefTable: 'sow_fund_sources',
      affectedRefId: fundSource.id,
      affectedField: 'declared_amount',
      autoGenerated: true,
    }];
  }
  return [];
}

/**
 * 2. Declared amount does not reconcile with linked transactions.
 */
export function detectAmountMismatch(
  fundSource: FundSourceRecord,
  linkedTransactions: TransactionRecord[]
): ContradictionResult[] {
  if (!fundSource.declared_amount || linkedTransactions.length === 0) return [];

  const txTotal = linkedTransactions.reduce(
    (sum, tx) => sum + (tx.amount ?? 0), 0
  );
  const diff = Math.abs(fundSource.declared_amount - txTotal);
  const threshold = fundSource.declared_amount * 0.1; // 10% tolerance

  if (diff > threshold) {
    return [{
      type: 'amount_mismatch',
      summary: `Declared £${fundSource.declared_amount} vs linked transactions total £${txTotal} (difference £${diff.toFixed(2)}).`,
      severity: diff > fundSource.declared_amount * 0.5 ? 'critical' : 'high',
      affectedRefTable: 'sow_fund_sources',
      affectedRefId: fundSource.id,
      affectedField: 'declared_amount',
      autoGenerated: true,
    }];
  }
  return [];
}

/**
 * 3. Salary savings claimed but salary pattern does not adequately support accumulation.
 */
export function detectSalaryAccumulationGap(
  fundSource: FundSourceRecord,
  incomeVerification: IncomeVerificationRecord | null
): ContradictionResult[] {
  // Placeholder: full logic requires comparing declared savings amount
  // against (avg_salary_credit × months) minus typical living costs.
  if (
    fundSource.source_category?.toLowerCase().includes('salary') &&
    fundSource.income_explains_savings &&
    incomeVerification &&
    fundSource.declared_amount &&
    incomeVerification.avg_salary_credit
  ) {
    const yearsStr = fundSource.years_to_accumulate ?? 1;
    const maxPlausible = incomeVerification.avg_salary_credit * 12 * Number(yearsStr) * 0.5;
    if (fundSource.declared_amount > maxPlausible && maxPlausible > 0) {
      return [{
        type: 'salary_accumulation_gap',
        summary: `Claims salary savings of £${fundSource.declared_amount} over ${yearsStr}yr but avg salary credit is £${incomeVerification.avg_salary_credit}/mo — max plausible savings ~£${maxPlausible.toFixed(0)}.`,
        severity: 'high',
        affectedRefTable: 'sow_fund_sources',
        affectedRefId: fundSource.id,
        affectedField: 'declared_amount',
        autoGenerated: true,
      }];
    }
  }
  return [];
}

/**
 * 4. Source marked as received on a date but no matching transaction exists.
 */
export function detectMissingTransactionForDate(
  fundSource: FundSourceRecord,
  transactions: TransactionRecord[]
): ContradictionResult[] {
  if (!fundSource.date_received) return [];

  const matchingTx = transactions.find(
    (tx) =>
      tx.tx_date === fundSource.date_received &&
      tx.linked_fund_source_id === fundSource.id
  );

  if (!matchingTx) {
    return [{
      type: 'missing_transaction_for_date',
      summary: `Source "${fundSource.source_category ?? 'unknown'}" claims receipt date ${fundSource.date_received} but no linked transaction found on that date.`,
      severity: 'medium',
      affectedRefTable: 'sow_fund_sources',
      affectedRefId: fundSource.id,
      affectedField: 'date_received',
      autoGenerated: true,
    }];
  }
  return [];
}

/**
 * 5. Manual balance counted toward proof but attachment/proof missing or weak.
 */
export function detectUnprovenManualBalance(
  manualBalance: ManualBalanceRecord
): ContradictionResult[] {
  if (
    manualBalance.counted_toward_proof &&
    (!manualBalance.attachment_name || manualBalance.evidence_status === 'unverified')
  ) {
    return [{
      type: 'unproven_manual_balance',
      summary: `Manual balance of £${manualBalance.amount ?? 0} is counted toward proof of funds but has no verified attachment.`,
      severity: 'high',
      affectedRefTable: 'sow_manual_balances',
      affectedRefId: manualBalance.id,
      affectedField: 'counted_toward_proof',
      autoGenerated: true,
    }];
  }
  return [];
}

/**
 * 6. Co-buyer contribution declared but not evidenced.
 */
export function detectUnevidencedCoBuyer(
  party: PartyRecord,
  fundSources: FundSourceRecord[]
): ContradictionResult[] {
  if (!party.contribution_amount || party.contribution_amount <= 0) return [];

  const partyFundSources = fundSources.filter(
    (fs) => fs.case_id === party.case_id
  );
  const anyEvidenced = partyFundSources.some(
    (fs) =>
      fs.verification_status &&
      fs.verification_status !== 'declared_only' &&
      fs.verification_status !== 'unverified'
  );

  if (!anyEvidenced) {
    return [{
      type: 'unevidenced_cobuyer',
      summary: `Co-buyer "${party.full_name}" declares contribution of £${party.contribution_amount} but no evidenced fund source found.`,
      severity: 'high',
      affectedRefTable: 'case_parties',
      affectedRefId: party.id,
      affectedField: 'contribution_amount',
      autoGenerated: true,
    }];
  }
  return [];
}

/**
 * 7. Gift declared but donor/evidence fields absent.
 */
export function detectGiftWithoutDonor(
  fundSource: FundSourceRecord
): ContradictionResult[] {
  if (fundSource.source_category?.toLowerCase().includes('gift')) {
    if (!fundSource.supporting_doc_uploaded && !fundSource.supporting_doc_name) {
      return [{
        type: 'gift_without_donor',
        summary: `Gift source declared (£${fundSource.declared_amount ?? 0}) but no supporting document or donor evidence provided.`,
        severity: 'high',
        affectedRefTable: 'sow_fund_sources',
        affectedRefId: fundSource.id,
        affectedField: 'supporting_doc_uploaded',
        autoGenerated: true,
      }];
    }
  }
  return [];
}

/**
 * 8. Funds claimed UK-based but evidence indicates otherwise.
 */
export function detectUKMismatch(
  fundSource: FundSourceRecord,
  accounts: ConnectedAccountRecord[]
): ContradictionResult[] {
  if (fundSource.outside_uk === false && fundSource.linked_account_ids?.length) {
    const nonGBP = accounts.filter(
      (a) =>
        fundSource.linked_account_ids!.includes(a.id) &&
        a.account_currency &&
        a.account_currency !== 'GBP'
    );
    if (nonGBP.length > 0) {
      return [{
        type: 'uk_mismatch',
        summary: `Source "${fundSource.source_category}" marked as UK-based but linked account(s) use non-GBP currency.`,
        severity: 'medium',
        affectedRefTable: 'sow_fund_sources',
        affectedRefId: fundSource.id,
        affectedField: 'outside_uk',
        autoGenerated: true,
      }];
    }
  }
  return [];
}

/**
 * 9. Bank data shows incoming credits not covered by any declared source.
 */
export function detectUndeclaredIncoming(
  transactions: TransactionRecord[],
  fundSources: FundSourceRecord[]
): ContradictionResult[] {
  const results: ContradictionResult[] = [];
  const incomingUnlinked = transactions.filter(
    (tx) =>
      tx.direction === 'incoming' &&
      !tx.linked_fund_source_id &&
      tx.explanation_status !== 'mapped' &&
      tx.explanation_status !== 'not_relevant'
  );

  // Flag significant unlinked incoming transactions
  for (const tx of incomingUnlinked) {
    if (tx.amount && tx.amount >= 1000) {
      results.push({
        type: 'undeclared_incoming',
        summary: `Incoming transaction of £${tx.amount} on ${tx.tx_date ?? 'unknown date'} ("${tx.description ?? ''}") is not linked to any declared source.`,
        severity: tx.amount >= 10000 ? 'critical' : 'high',
        affectedRefTable: 'sow_transactions',
        affectedRefId: tx.id,
        affectedField: 'linked_fund_source_id',
        autoGenerated: true,
      });
    }
  }
  return results;
}

/**
 * 10. "No mortgage" declared but mortgage amount/lender fields populated.
 */
export function detectMortgageContradiction(
  reportData: ReportHeaderRecord
): ContradictionResult[] {
  const hasMortgageData =
    (reportData.mortgage_amount && reportData.mortgage_amount > 0) ||
    (reportData.mortgage_lender && reportData.mortgage_lender.trim().length > 0);
  const noMortgage = reportData.mortgage_offer_in_place === false;

  if (noMortgage && hasMortgageData) {
    return [{
      type: 'mortgage_contradiction',
      summary: `Report indicates no mortgage offer in place, but mortgage amount (£${reportData.mortgage_amount ?? 0}) or lender ("${reportData.mortgage_lender ?? ''}") is populated.`,
      severity: 'high',
      affectedRefTable: 'armalytix_reports',
      affectedRefId: '', // caller must supply
      affectedField: 'mortgage_offer_in_place',
      autoGenerated: true,
    }];
  }
  return [];
}

/**
 * 11. Inconsistent names across payslip, account holder and declared employer.
 */
export function detectNameMismatch(
  incomeVerification: IncomeVerificationRecord | null,
  accounts: ConnectedAccountRecord[],
  fundSources: FundSourceRecord[]
): ContradictionResult[] {
  if (!incomeVerification) return [];

  const results: ContradictionResult[] = [];

  // Check payslip name match flag
  if (incomeVerification.payslip_name_match === false) {
    results.push({
      type: 'name_mismatch',
      summary: 'Payslip name does not match the expected client name.',
      severity: 'high',
      affectedRefTable: 'sow_income_verification',
      affectedRefId: incomeVerification.id,
      affectedField: 'payslip_name_match',
      autoGenerated: true,
    });
  }

  // Check employer name consistency
  const salarySource = fundSources.find(
    (fs) => fs.source_category?.toLowerCase().includes('salary')
  );
  if (
    salarySource?.employer_name &&
    incomeVerification.matched_employer_name &&
    salarySource.employer_name.toLowerCase() !== incomeVerification.matched_employer_name.toLowerCase()
  ) {
    results.push({
      type: 'name_mismatch',
      summary: `Declared employer "${salarySource.employer_name}" does not match bank-matched employer "${incomeVerification.matched_employer_name}".`,
      severity: 'medium',
      affectedRefTable: 'sow_fund_sources',
      affectedRefId: salarySource.id,
      affectedField: 'employer_name',
      autoGenerated: true,
    });
  }

  return results;
}

// ── Orchestrator ─────────────────────────────────────────────────

export interface ContradictionCheckInputs {
  fundSources: FundSourceRecord[];
  evidenceItems: EvidenceItemRecord[];
  transactions: TransactionRecord[];
  manualBalances: ManualBalanceRecord[];
  parties: PartyRecord[];
  incomeVerifications: IncomeVerificationRecord[];
  accounts: ConnectedAccountRecord[];
  reportHeader: ReportHeaderRecord | null;
}

/**
 * Run all contradiction checks and return a flat array of results.
 */
export function runAllContradictionChecks(
  inputs: ContradictionCheckInputs
): ContradictionResult[] {
  const results: ContradictionResult[] = [];

  // Per fund-source checks
  for (const fs of inputs.fundSources) {
    results.push(...detectUnevidencedSource(fs, inputs.evidenceItems));
    results.push(
      ...detectAmountMismatch(
        fs,
        inputs.transactions.filter((tx) => tx.linked_fund_source_id === fs.id)
      )
    );
    const iv = inputs.incomeVerifications.find(
      (v) => v.id // placeholder: match by party_id or fund_source_id in real usage
    );
    results.push(...detectSalaryAccumulationGap(fs, iv ?? null));
    results.push(...detectMissingTransactionForDate(fs, inputs.transactions));
    results.push(...detectGiftWithoutDonor(fs));
    results.push(...detectUKMismatch(fs, inputs.accounts));
  }

  // Per manual-balance checks
  for (const mb of inputs.manualBalances) {
    results.push(...detectUnprovenManualBalance(mb));
  }

  // Per party checks
  for (const party of inputs.parties) {
    results.push(...detectUnevidencedCoBuyer(party, inputs.fundSources));
  }

  // Cross-cutting checks
  results.push(...detectUndeclaredIncoming(inputs.transactions, inputs.fundSources));

  if (inputs.reportHeader) {
    results.push(...detectMortgageContradiction(inputs.reportHeader));
  }

  // Name mismatch (uses first income verification for simplicity)
  results.push(
    ...detectNameMismatch(
      inputs.incomeVerifications[0] ?? null,
      inputs.accounts,
      inputs.fundSources
    )
  );

  return results;
}

// ── Full Analysis Orchestrator ───────────────────────────────────
// Chains all 5 analysis modules into a single pipeline.

export interface FullAnalysisInputs {
  /** Raw transactions from sow_transactions */
  transactions: RawTransaction[];
  /** Classification context (accounts, parties, fund sources) */
  classificationContext: ClassificationContext;
  /** Fund sources with declared amounts for matching */
  matchableFundSources: MatchableFundSource[];
  /** Materiality context */
  materialityContext: MaterialityContext;
  /** Optional materiality config overrides */
  materialityConfig?: Partial<MaterialityConfig>;
  /** Reconciliation inputs (broader data set) */
  reconciliationInputs: Omit<ReconciliationInputs, 'classifiedTransactions' | 'matchedCandidates'>;
  /** Existing contradiction check inputs */
  contradictionCheckInputs: ContradictionCheckInputs;
  /** Optional A7 inputs — lifestyle vs declared income */
  lifestyleInputs?: import('./exceptionEngine').LifestyleProportionalityInputs;
  /** Optional A12 inputs — disclosure timing */
  disclosureTimingInputs?: import('./exceptionEngine').DisclosureTimingInputs;
  /** Optional A1 inputs — purchaser count contradiction */
  purchaserCountInputs?: import('./exceptionEngine').PurchaserCountInputs;
  /** Optional B3 inputs — gift declared vs denied */
  giftDeclarationInputs?: import('./exceptionEngine').GiftDeclarationInputs;
  /** Optional C5 inputs — employment status contradiction */
  employmentStatusInputs?: import('./exceptionEngine').EmploymentStatusInputs;
}

export interface FullAnalysisResult {
  /** Layer 1: Classified transactions */
  classifiedTransactions: ClassifiedTransaction[];
  /** Layer 1b: Materiality assessments sorted by score */
  materialityAssessments: MaterialityAssessment[];
  /** Layer 1b: Repeated unexplained patterns */
  repeatedPatterns: RepeatedPattern[];
  /** Layer 2: Transaction ↔ source match results */
  matchResult: MatchResult;
  /** Layer 2: Per-source reconciliation */
  sourceReconciliations: SourceReconciliation[];
  /** Layer 2: Matter-level funding chain */
  fundingChain: FundingChainSummary;
  /** Existing contradiction checks */
  contradictions: ContradictionResult[];
  /** Layer 3: Structured exceptions */
  exceptions: ExceptionItem[];
  /** Layer 3: Grouped exceptions ledger */
  exceptionsLedger: ExceptionsLedger;
  /** Layer 4: Draft enquiries */
  draftEnquiries: DraftEnquiry[];
  /** Layer 4: Reviewer-facing summary */
  reviewerSummary: ReviewerSummary;
  /** Layer 4: Decision-support outputs */
  decisionSupport: DecisionSupportOutput;
}

/**
 * Run the full analysis pipeline:
 * 1. classifyAllTransactions
 * 2. assessBulkMateriality + detectRepeatedPatterns
 * 3. matchAllTransactions
 * 4. reconcileAllSources + buildFundingChain
 * 5. runAllContradictionChecks (existing)
 * 6. generateExceptions
 * 7. generateDraftEnquiries
 * 8. buildReviewerSummary + buildDecisionSupport
 */
export function runFullAnalysis(inputs: FullAnalysisInputs): FullAnalysisResult {
  // Layer 1: Classify
  const classifiedTransactions = classifyAllTransactions(
    inputs.transactions,
    inputs.classificationContext
  );

  // Layer 1b: Materiality triage
  const materialityAssessments = assessBulkMateriality(
    classifiedTransactions,
    inputs.materialityContext
  );
  const cfg: MaterialityConfig = { ...DEFAULT_MATERIALITY_CONFIG, ...inputs.materialityConfig };
  const repeatedPatterns = detectRepeatedPatterns(classifiedTransactions, cfg);

  // Layer 2: Match
  const matchResult = matchAllTransactions(
    classifiedTransactions,
    inputs.matchableFundSources,
    inputs.classificationContext.accounts,
    inputs.classificationContext.parties
  );

  // Layer 2: Reconcile
  const reconInputs: ReconciliationInputs = {
    ...inputs.reconciliationInputs,
    classifiedTransactions,
    matchedCandidates: matchResult.matched,
  };
  const sourceReconciliations = reconcileAllSources(reconInputs);
  const fundingChain = buildFundingChain(reconInputs, sourceReconciliations);

  // Existing contradiction checks
  const contradictions = runAllContradictionChecks(inputs.contradictionCheckInputs);

  // Layer 3: Exceptions
  // Enrich giftDeclarationInputs with classifier output so the high-confidence
  // 'gift' category signal can fire even when callers pass raw (unclassified)
  // transactions. The rule itself remains pure — it just sees `classifiedCategory`.
  const enrichedGiftInputs = inputs.giftDeclarationInputs
    ? {
        ...inputs.giftDeclarationInputs,
        transactions: inputs.giftDeclarationInputs.transactions.map((t) => {
          const classified = classifiedTransactions.find((c) => c.id === t.id);
          return {
            ...t,
            classifiedCategory: t.classifiedCategory ?? classified?.classifiedCategory ?? null,
          };
        }),
      }
    : undefined;

  const exceptions = generateExceptions({
    reconciliations: sourceReconciliations,
    fundingChain,
    classifiedTransactions,
    materialityAssessments,
    repeatedPatterns,
    contradictions,
    lifestyleInputs: inputs.lifestyleInputs,
    disclosureTimingInputs: inputs.disclosureTimingInputs,
    purchaserCountInputs: inputs.purchaserCountInputs,
    giftDeclarationInputs: enrichedGiftInputs,
    employmentStatusInputs: inputs.employmentStatusInputs,
  });

  const exceptionsLedger = buildExceptionsLedger(exceptions);

  // Layer 4: Enquiries
  const draftEnquiries = generateDraftEnquiries({
    exceptions,
    reconciliations: sourceReconciliations,
    fundingChain,
    unmatchedTxIds: matchResult.unmatched,
  });

  // Layer 4: Reviewer summary
  const reviewerSummary = buildReviewerSummary({
    reconciliations: sourceReconciliations,
    fundingChain,
    exceptions,
    unmatchedTxIds: matchResult.unmatched,
    classifiedTransactions,
    draftEnquiries,
  });

  // Layer 4: Decision support
  const decisionSupport = buildDecisionSupport(
    reviewerSummary,
    fundingChain,
    exceptionsLedger,
    draftEnquiries
  );

  return {
    classifiedTransactions,
    materialityAssessments,
    repeatedPatterns,
    matchResult,
    sourceReconciliations,
    fundingChain,
    contradictions,
    exceptions,
    exceptionsLedger,
    draftEnquiries,
    reviewerSummary,
    decisionSupport,
  };
}