/**
 * Exception / Risk Item Generation Engine — Layer 3
 *
 * Creates structured, rule-backed exceptions from reconciliation
 * and classification outputs. Each rule is a named function.
 *
 * Pure functions — no DB calls.
 */

import type { SourceReconciliation, FundingChainSummary } from './reconciliationEngine';
import type { ClassifiedTransaction } from './transactionClassifier';
import type { MaterialityAssessment, RepeatedPattern } from './materialityEngine';
import type { ContradictionResult } from './provenanceTypes';

// ── Exception item ───────────────────────────────────────────────

export const EXCEPTION_TYPES = [
  'undeclared_incoming_credit',
  'unexplained_large_incoming',
  'repeated_third_party_credits',
  'cash_deposit_unexplained',
  'salary_savings_unsupported',
  'cobuyer_contribution_unevidenced',
  'gift_incomplete_evidence',
  'manual_balance_unevidenced',
  'funding_shortfall',
  'excess_funds_unexplained',
  'amount_mismatch_declaration_vs_evidence',
  'source_timing_mismatch',
  'transaction_inconsistent_with_source',
  'possible_undeclared_loan',
  'investment_crypto_activity',
  'significant_gambling_activity',
  'transfer_chain_unclear',
  'circular_movement_suspected',
  'overseas_insufficiently_explained',
  'mortgage_funding_contradiction',
  'name_identity_inconsistency',
  // A7 — Lifestyle / income proportionality
  'lifestyle_inconsistent_with_income',
  // A12 — Disclosure timing
  'late_disclosure_after_challenge',
  // A1 — Purchaser count contradiction (PIF declared parties vs Armalytix-detected buyers / mortgage co-borrowers)
  'purchaser_count_contradiction',
  // B3 — Gift declared vs denied (PIF says no gift but Armalytix evidence shows gift-shaped funds)
  'gift_declared_vs_denied',
  // C5 — Employment status contradiction (declared salary but evidence indicates self-employment)
  'employment_status_contradiction',
] as const;

export type ExceptionType = (typeof EXCEPTION_TYPES)[number];

export interface ExceptionItem {
  exceptionType: ExceptionType;
  severity: 'critical' | 'high' | 'medium' | 'low';
  rationale: string;
  quantitativeBasis: string | null;
  linkedRefTable: string;
  linkedRefId: string;
  linkedField: string | null;
  autoGenerated: boolean;
  reviewerConfirmationRequired: boolean;
  /** Placeholder hook for future enquiry-generation engine */
  suggestedNextAction: string;
  canTriggerEnquiry: boolean;
}

// ── DB-ready risk flag mapping ───────────────────────────────────

export interface RiskFlagInsert {
  case_id: string;
  armalytix_report_id: string;
  flag_type: string;
  severity: string;
  rationale: string;
  contradiction_type: string | null;
  contradiction_summary: string | null;
  affected_ref_table: string;
  affected_ref_id: string;
  affected_field: string | null;
  auto_generated: boolean;
}

export function toRiskFlagInsert(
  exception: ExceptionItem,
  caseId: string,
  reportId: string
): RiskFlagInsert {
  return {
    case_id: caseId,
    armalytix_report_id: reportId,
    flag_type: exception.exceptionType,
    severity: exception.severity,
    rationale: exception.rationale,
    contradiction_type: exception.exceptionType,
    contradiction_summary: exception.rationale,
    affected_ref_table: exception.linkedRefTable,
    affected_ref_id: exception.linkedRefId,
    affected_field: exception.linkedField,
    auto_generated: exception.autoGenerated,
  };
}

// ── Rule functions ───────────────────────────────────────────────

function ruleUndeclaredIncoming(
  assessments: MaterialityAssessment[],
  txs: ClassifiedTransaction[]
): ExceptionItem[] {
  const results: ExceptionItem[] = [];
  for (const a of assessments) {
    const tx = a.classifiedTransaction;
    if (
      tx.direction === 'incoming' &&
      !tx.linked_fund_source_id &&
      tx.explanation_status !== 'mapped' &&
      tx.explanation_status !== 'not_relevant' &&
      (tx.amount ?? 0) >= 1000
    ) {
      results.push({
        exceptionType: 'undeclared_incoming_credit',
        severity: (tx.amount ?? 0) >= 10_000 ? 'critical' : 'high',
        rationale: `Incoming credit of £${tx.amount} on ${tx.tx_date ?? 'unknown'} ("${tx.description ?? ''}") not linked to any declared source.`,
        quantitativeBasis: `£${tx.amount}`,
        linkedRefTable: 'sow_transactions',
        linkedRefId: tx.id,
        linkedField: 'linked_fund_source_id',
        autoGenerated: true,
        reviewerConfirmationRequired: true,
        suggestedNextAction: 'ENQUIRY: Request explanation and evidence for this credit.',
        canTriggerEnquiry: true,
      });
    }
  }
  return results;
}

/** Categories that should NOT trigger unexplained_large_incoming when classified with high confidence */
const SAFE_LARGE_CATEGORIES = new Set([
  'salary_credit',
  'bonus_credit',
  'government_bonus',
  'sale_proceeds',
  'investment_withdrawal',
  'refund',
]);

function ruleUnexplainedLargeIncoming(
  assessments: MaterialityAssessment[],
  amountToProve?: number
): ExceptionItem[] {
  const results: ExceptionItem[] = [];
  for (const a of assessments) {
    const tx = a.classifiedTransaction;
    const amt = tx.amount ?? 0;
    const isLarge = amt >= 5000 || tx.is_large === true;

    if (!isLarge || tx.direction !== 'incoming' || tx.linked_fund_source_id) continue;

    // High-confidence safe categories (salary, bonus, refund, etc.) — skip
    const conf = typeof tx.classificationConfidence === 'number' ? tx.classificationConfidence : 0;
    const isSafe = SAFE_LARGE_CATEGORIES.has(tx.classifiedCategory) && conf >= 0.8;
    const isGiftHighConf = tx.classifiedCategory === 'gift' && conf >= 0.8;

    if (isSafe || isGiftHighConf) continue;

    // Severity: proportion-based when amountToProve is available
    let severity: 'critical' | 'high' | 'medium';
    if (amountToProve && amountToProve > 0 && amt / amountToProve > 0.2) {
      severity = 'critical';
    } else if (amt >= 5000) {
      severity = 'high';
    } else {
      severity = 'medium';
    }

    results.push({
      exceptionType: 'unexplained_large_incoming',
      severity,
      rationale: `Large incoming credit of £${amt} on ${tx.tx_date ?? 'unknown'} ("${tx.description ?? ''}") is unexplained or only weakly classified (category: ${tx.classifiedCategory}, confidence: ${(conf * 100).toFixed(0)}%).`,
      quantitativeBasis: `£${amt}`,
      linkedRefTable: 'sow_transactions',
      linkedRefId: tx.id,
      linkedField: null,
      autoGenerated: true,
      reviewerConfirmationRequired: true,
      suggestedNextAction: 'ENQUIRY: Identify source and request supporting evidence for this credit.',
      canTriggerEnquiry: true,
    });
  }
  return results;
}

const REPEATED_RISK_CATEGORIES = new Set([
  'third_party_transfer',
  'unknown_incoming',
  'own_account_transfer',
  'recurring_non_salary',
]);

function ruleRepeatedThirdParty(
  repeatedPatterns: RepeatedPattern[]
): ExceptionItem[] {
  const results: ExceptionItem[] = [];
  for (const p of repeatedPatterns) {
    if (REPEATED_RISK_CATEGORIES.has(p.category)) {
      results.push({
        exceptionType: 'repeated_third_party_credits',
        severity: p.totalAmount >= 10_000 ? 'critical' : 'high',
        rationale: `${p.count} repeated ${p.category} credits totalling £${p.totalAmount.toFixed(2)} without explanation.`,
        quantitativeBasis: `${p.count} transactions, £${p.totalAmount.toFixed(2)} total`,
        linkedRefTable: 'sow_transactions',
        linkedRefId: p.transactionIds[0] ?? '',
        linkedField: null,
        autoGenerated: true,
        reviewerConfirmationRequired: true,
        suggestedNextAction: 'ENQUIRY: Request identity and purpose of recurring third-party payments.',
        canTriggerEnquiry: true,
      });
    }
  }
  return results;
}

function ruleCashDeposit(txs: ClassifiedTransaction[]): ExceptionItem[] {
  const results: ExceptionItem[] = [];
  const cashTxs = txs.filter(
    (t) => t.direction === 'incoming' && t.classifiedCategory === 'cash_deposit' && (t.amount ?? 0) >= 500
  );
  for (const tx of cashTxs) {
    results.push({
      exceptionType: 'cash_deposit_unexplained',
      severity: (tx.amount ?? 0) >= 5000 ? 'critical' : 'high',
      rationale: `Cash deposit of £${tx.amount} on ${tx.tx_date ?? 'unknown'}. Cash deposits require enhanced scrutiny.`,
      quantitativeBasis: `£${tx.amount}`,
      linkedRefTable: 'sow_transactions',
      linkedRefId: tx.id,
      linkedField: null,
      autoGenerated: true,
      reviewerConfirmationRequired: true,
      suggestedNextAction: 'ENQUIRY: Request explanation and evidence of cash origin.',
      canTriggerEnquiry: true,
    });
  }
  return results;
}

function ruleReconciliationExceptions(
  reconciliations: SourceReconciliation[]
): ExceptionItem[] {
  const results: ExceptionItem[] = [];

  for (const r of reconciliations) {
    const cat = r.sourceCategory.toLowerCase();

    // Amount mismatch
    if (r.unsupportedAmount > 0 && r.declaredAmount > 0 && r.unsupportedAmount / r.declaredAmount > 0.1) {
      results.push({
        exceptionType: 'amount_mismatch_declaration_vs_evidence',
        severity: r.unsupportedAmount / r.declaredAmount > 0.5 ? 'critical' : 'high',
        rationale: `Source "${r.sourceCategory}": £${r.unsupportedAmount.toFixed(2)} unsupported of £${r.declaredAmount} declared.`,
        quantitativeBasis: `Supported: £${r.supportedAmount.toFixed(2)}, Unsupported: £${r.unsupportedAmount.toFixed(2)}`,
        linkedRefTable: 'sow_fund_sources',
        linkedRefId: r.fundSourceId,
        linkedField: 'declared_amount',
        autoGenerated: true,
        reviewerConfirmationRequired: true,
        suggestedNextAction: 'ENQUIRY: Request further evidence or explanation for the unsupported amount.',
        canTriggerEnquiry: true,
      });
    }

    // Timing mismatch
    if (r.timingMismatch) {
      results.push({
        exceptionType: 'source_timing_mismatch',
        severity: 'medium',
        rationale: `Source "${r.sourceCategory}" declared receipt date does not align with linked transaction dates.`,
        quantitativeBasis: null,
        linkedRefTable: 'sow_fund_sources',
        linkedRefId: r.fundSourceId,
        linkedField: 'date_received',
        autoGenerated: true,
        reviewerConfirmationRequired: true,
        suggestedNextAction: 'ENQUIRY: Clarify the date funds were received.',
        canTriggerEnquiry: true,
      });
    }

    // Circular movement
    if (r.circularMovementDetected) {
      results.push({
        exceptionType: 'circular_movement_suspected',
        severity: 'critical',
        rationale: `Source "${r.sourceCategory}": transactions suggest possible circular movement of funds between accounts.`,
        quantitativeBasis: `Declared: £${r.declaredAmount}`,
        linkedRefTable: 'sow_fund_sources',
        linkedRefId: r.fundSourceId,
        linkedField: null,
        autoGenerated: true,
        reviewerConfirmationRequired: true,
        suggestedNextAction: 'ENQUIRY: Request full audit trail showing origin and destination of funds.',
        canTriggerEnquiry: true,
      });
    }

    // Salary savings unsupported
    if (cat.includes('salary') && r.reconciliationStatus !== 'fully_reconciled' && r.mismatchReasons.some((m) => m.includes('accumulation'))) {
      results.push({
        exceptionType: 'salary_savings_unsupported',
        severity: 'high',
        rationale: `Salary savings claim of £${r.declaredAmount} not adequately supported by income pattern.`,
        quantitativeBasis: `Declared: £${r.declaredAmount}, Supported: £${r.supportedAmount.toFixed(2)}`,
        linkedRefTable: 'sow_fund_sources',
        linkedRefId: r.fundSourceId,
        linkedField: 'declared_amount',
        autoGenerated: true,
        reviewerConfirmationRequired: true,
        suggestedNextAction: 'ENQUIRY: Request savings history and detailed explanation of accumulation.',
        canTriggerEnquiry: true,
      });
    }

    // Co-buyer unevidenced — fires when unreconciled, pending review, OR no independent evidence
    if (
      (cat.includes('co-buyer') || cat.includes('co_buyer')) &&
      (r.reconciliationStatus === 'unreconciled' ||
       r.reconciliationStatus === 'pending_review' ||
       r.linkedEvidenceCount === 0)
    ) {
      const noEvidence = r.linkedEvidenceCount === 0;
      results.push({
        exceptionType: 'cobuyer_contribution_unevidenced',
        severity: 'high',
        rationale: noEvidence && r.reconciliationStatus !== 'unreconciled'
          ? `Co-buyer contribution of £${r.declaredAmount} has an inferred transaction match but no independent evidence (no linked evidence items).`
          : `Co-buyer contribution of £${r.declaredAmount} has no supporting evidence.`,
        quantitativeBasis: `£${r.declaredAmount}`,
        linkedRefTable: 'sow_fund_sources',
        linkedRefId: r.fundSourceId,
        linkedField: 'declared_amount',
        autoGenerated: true,
        reviewerConfirmationRequired: true,
        suggestedNextAction: 'ENQUIRY: Request bank statements and source evidence from co-buyer.',
        canTriggerEnquiry: true,
      });
    }

    // Gift incomplete
    if (cat.includes('gift') && (r.reconciliationStatus === 'unreconciled' || r.linkedEvidenceCount === 0)) {
      results.push({
        exceptionType: 'gift_incomplete_evidence',
        severity: 'high',
        rationale: `Gift of £${r.declaredAmount} lacks complete evidence (donor letter, bank statement, or relationship proof).`,
        quantitativeBasis: `£${r.declaredAmount}`,
        linkedRefTable: 'sow_fund_sources',
        linkedRefId: r.fundSourceId,
        linkedField: null,
        autoGenerated: true,
        reviewerConfirmationRequired: true,
        suggestedNextAction: 'ENQUIRY: Request gift letter, donor bank statement, and proof of donor relationship.',
        canTriggerEnquiry: true,
      });
    }
  }

  return results;
}

function ruleFundingChainExceptions(chain: FundingChainSummary): ExceptionItem[] {
  const results: ExceptionItem[] = [];

  if (chain.hasShortfall) {
    const shortfallProportion = chain.amountToProve > 0
      ? chain.shortfallAmount / chain.amountToProve : 1;

    // Cross-check: if report header says no shortfall, downgrade
    const reportSaysNoShortfall = chain.reportHeaderExcessShortfall != null
      && chain.reportHeaderExcessShortfall >= 0;

    // Materiality gate: trivial shortfalls get suppressed or downgraded
    const isTrivial = shortfallProportion < 0.05 && chain.shortfallAmount < 2000;

    if (!(reportSaysNoShortfall && isTrivial)) {
      // Determine severity with nuance
      let severity: 'critical' | 'high' | 'medium' | 'low';
      if (reportSaysNoShortfall || isTrivial) {
        severity = 'low';
      } else if (shortfallProportion > 0.2) {
        severity = 'critical';
      } else {
        severity = 'high';
      }

      results.push({
        exceptionType: 'funding_shortfall',
        severity,
        rationale: `Funding shortfall of £${chain.shortfallAmount.toFixed(2)}. Amount to prove: £${chain.amountToProve}, evidenced: £${chain.totalEvidencedFunds.toFixed(2)}.${reportSaysNoShortfall ? ' Note: Armalytix report header indicates no shortfall — gap may reflect limited transaction visibility.' : ''}`,
        quantitativeBasis: `Shortfall: £${chain.shortfallAmount.toFixed(2)} (${(shortfallProportion * 100).toFixed(1)}% of amount to prove)`,
        linkedRefTable: 'armalytix_reports',
        linkedRefId: '',
        linkedField: 'amount_to_prove',
        autoGenerated: true,
        reviewerConfirmationRequired: true,
        suggestedNextAction: 'ENQUIRY: Request explanation and evidence for funding gap.',
        canTriggerEnquiry: true,
      });
    }
  }

  if (chain.hasExcess && !chain.excessExplained) {
    results.push({
      exceptionType: 'excess_funds_unexplained',
      severity: 'medium',
      rationale: `Excess funds of £${chain.excessAmount.toFixed(2)} above amount to prove. The excess is not fully explained.`,
      quantitativeBasis: `Excess: £${chain.excessAmount.toFixed(2)}`,
      linkedRefTable: 'armalytix_reports',
      linkedRefId: '',
      linkedField: 'excess_shortfall',
      autoGenerated: true,
      reviewerConfirmationRequired: false,
      suggestedNextAction: 'NOTE: Consider whether excess requires further investigation.',
      canTriggerEnquiry: false,
    });
  }

  if (chain.unsupportedManualBalances > 0) {
    results.push({
      exceptionType: 'manual_balance_unevidenced',
      severity: 'high',
      rationale: `Manual balances of £${chain.unsupportedManualBalances.toFixed(2)} relied upon for proof of funds but lacking evidence.`,
      quantitativeBasis: `£${chain.unsupportedManualBalances.toFixed(2)}`,
      linkedRefTable: 'sow_manual_balances',
      linkedRefId: '',
      linkedField: 'counted_toward_proof',
      autoGenerated: true,
      reviewerConfirmationRequired: true,
      suggestedNextAction: 'ENQUIRY: Request verified bank statement or screenshot for manual balance.',
      canTriggerEnquiry: true,
    });
  }

  if (chain.giftsUnproven > 0) {
    results.push({
      exceptionType: 'gift_incomplete_evidence',
      severity: 'high',
      rationale: `Gift funds of £${chain.giftsUnproven.toFixed(2)} declared but not adequately evidenced.`,
      quantitativeBasis: `£${chain.giftsUnproven.toFixed(2)}`,
      linkedRefTable: 'sow_fund_sources',
      linkedRefId: '',
      linkedField: null,
      autoGenerated: true,
      reviewerConfirmationRequired: true,
      suggestedNextAction: 'ENQUIRY: Request gift letter, donor bank statement, and proof of donor SoW.',
      canTriggerEnquiry: true,
    });
  }

  if (chain.coBuyerUnproven > 0) {
    results.push({
      exceptionType: 'cobuyer_contribution_unevidenced',
      severity: 'high',
      rationale: `Co-buyer contributions of £${chain.coBuyerUnproven.toFixed(2)} declared but not evidenced.`,
      quantitativeBasis: `£${chain.coBuyerUnproven.toFixed(2)}`,
      linkedRefTable: 'case_parties',
      linkedRefId: '',
      linkedField: 'contribution_amount',
      autoGenerated: true,
      reviewerConfirmationRequired: true,
      suggestedNextAction: 'ENQUIRY: Request co-buyer bank statements and source of funds evidence.',
      canTriggerEnquiry: true,
    });
  }

  return results;
}

function ruleActivityExceptions(txs: ClassifiedTransaction[]): ExceptionItem[] {
  const results: ExceptionItem[] = [];

  // Gambling
  const gamblingTxs = txs.filter((t) => t.classifiedCategory === 'gambling');
  const totalGambling = gamblingTxs.reduce((s, t) => s + (t.amount ?? 0), 0);
  if (totalGambling >= 500) {
    results.push({
      exceptionType: 'significant_gambling_activity',
      severity: totalGambling >= 5000 ? 'critical' : 'high',
      rationale: `${gamblingTxs.length} gambling transactions totalling £${totalGambling.toFixed(2)} detected.`,
      quantitativeBasis: `${gamblingTxs.length} transactions, £${totalGambling.toFixed(2)}`,
      linkedRefTable: 'sow_transactions',
      linkedRefId: gamblingTxs[0]?.id ?? '',
      linkedField: null,
      autoGenerated: true,
      reviewerConfirmationRequired: true,
      suggestedNextAction: 'ENQUIRY: Assess impact on relied-upon funds; request explanation if funds are being relied upon.',
      canTriggerEnquiry: true,
    });
  }

  // Crypto / investment
  const cryptoTxs = txs.filter((t) => t.classifiedCategory === 'crypto' || t.classifiedCategory === 'investment');
  const totalCrypto = cryptoTxs.reduce((s, t) => s + (t.amount ?? 0), 0);
  if (totalCrypto >= 500) {
    results.push({
      exceptionType: 'investment_crypto_activity',
      severity: totalCrypto >= 10_000 ? 'high' : 'medium',
      rationale: `${cryptoTxs.length} investment/crypto transactions totalling £${totalCrypto.toFixed(2)} detected.`,
      quantitativeBasis: `${cryptoTxs.length} transactions, £${totalCrypto.toFixed(2)}`,
      linkedRefTable: 'sow_transactions',
      linkedRefId: cryptoTxs[0]?.id ?? '',
      linkedField: null,
      autoGenerated: true,
      reviewerConfirmationRequired: true,
      suggestedNextAction: 'ENQUIRY: Determine if investment proceeds are relied upon for purchase.',
      canTriggerEnquiry: true,
    });
  }

  // Possible undeclared loan
  const loanTxs = txs.filter(
    (t) => t.direction === 'incoming' && t.classifiedCategory === 'loan_receipt' && !t.linked_fund_source_id
  );
  for (const tx of loanTxs) {
    results.push({
      exceptionType: 'possible_undeclared_loan',
      severity: 'high',
      rationale: `Incoming credit of £${tx.amount} on ${tx.tx_date ?? 'unknown'} appears loan-related but no loan declared in sources.`,
      quantitativeBasis: `£${tx.amount}`,
      linkedRefTable: 'sow_transactions',
      linkedRefId: tx.id,
      linkedField: null,
      autoGenerated: true,
      reviewerConfirmationRequired: true,
      suggestedNextAction: 'ENQUIRY: Clarify whether this is a loan and request loan agreement if applicable.',
      canTriggerEnquiry: true,
    });
  }

  // Overseas unexplained
  const overseasTxs = txs.filter(
    (t) => t.direction === 'incoming' && t.classifiedCategory === 'overseas_incoming' && !t.linked_fund_source_id
  );
  for (const tx of overseasTxs) {
    results.push({
      exceptionType: 'overseas_insufficiently_explained',
      severity: 'high',
      rationale: `Overseas incoming credit of £${tx.amount} on ${tx.tx_date ?? 'unknown'} not linked to a declared source.`,
      quantitativeBasis: `£${tx.amount}`,
      linkedRefTable: 'sow_transactions',
      linkedRefId: tx.id,
      linkedField: null,
      autoGenerated: true,
      reviewerConfirmationRequired: true,
      suggestedNextAction: 'ENQUIRY: Request originating country, institution, currency details, and purpose.',
      canTriggerEnquiry: true,
    });
  }

  return results;
}

function ruleContradictionBridge(contradictions: ContradictionResult[]): ExceptionItem[] {
  const results: ExceptionItem[] = [];

  for (const c of contradictions) {
    // Map existing contradiction types to exception types where applicable
    let exType: ExceptionType | null = null;
    if (c.type === 'mortgage_contradiction') exType = 'mortgage_funding_contradiction';
    else if (c.type === 'name_mismatch') exType = 'name_identity_inconsistency';
    else continue; // Already covered by other rules

    results.push({
      exceptionType: exType,
      severity: c.severity,
      rationale: c.summary,
      quantitativeBasis: null,
      linkedRefTable: c.affectedRefTable,
      linkedRefId: c.affectedRefId,
      linkedField: c.affectedField ?? null,
      autoGenerated: c.autoGenerated,
      reviewerConfirmationRequired: true,
      suggestedNextAction: 'ENQUIRY: Investigate and resolve the identified contradiction.',
      canTriggerEnquiry: true,
    });
  }

  return results;
}

// ── Deduplication ────────────────────────────────────────────────

function deduplicateExceptions(exceptions: ExceptionItem[]): ExceptionItem[] {
  const seen = new Set<string>();
  return exceptions.filter((e) => {
    const key = `${e.exceptionType}::${e.linkedRefTable}::${e.linkedRefId}::${e.linkedField ?? ''}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

// ── Orchestrator ─────────────────────────────────────────────────

export interface ExceptionGenerationInputs {
  reconciliations: SourceReconciliation[];
  fundingChain: FundingChainSummary;
  classifiedTransactions: ClassifiedTransaction[];
  materialityAssessments: MaterialityAssessment[];
  repeatedPatterns: RepeatedPattern[];
  contradictions: ContradictionResult[];
  /** Optional inputs for A7 — lifestyle vs declared income proportionality */
  lifestyleInputs?: LifestyleProportionalityInputs;
  /** Optional inputs for A12 — disclosure timing */
  disclosureTimingInputs?: DisclosureTimingInputs;
  /** Optional inputs for A1 — purchaser count contradiction */
  purchaserCountInputs?: PurchaserCountInputs;
  /** Optional inputs for B3 — gift declared vs denied */
  giftDeclarationInputs?: GiftDeclarationInputs;
  /** Optional inputs for C5 — employment status contradiction */
  employmentStatusInputs?: EmploymentStatusInputs;
}

// ── A1 — Purchaser count / co-borrower contradiction ─────────────

export interface PurchaserCountPartyInput {
  id: string;
  full_name?: string | null;
  role?: string | null;
  on_mortgage?: boolean | null;
  contribution_amount?: number | null;
}

export interface PurchaserCountInputs {
  /** Parties recorded in case_parties for this matter */
  parties: PurchaserCountPartyInput[];
  /**
   * Optional: number of buyers detected by Armalytix (e.g. report header
   * `numberOfBuyers` once mapped). When provided, an exact mismatch with
   * the declared purchaser count emits the contradiction.
   */
  armalytixDetectedBuyerCount?: number | null;
}

const PURCHASER_ROLE_TOKENS = ['purchaser', 'buyer', 'applicant'];

function isPurchaserRole(role: string | null | undefined): boolean {
  if (!role) return false;
  const r = role.toLowerCase();
  return PURCHASER_ROLE_TOKENS.some((t) => r.includes(t));
}

export function rulePurchaserCountContradiction(
  inputs?: PurchaserCountInputs,
): ExceptionItem[] {
  if (!inputs) return [];
  const parties = inputs.parties ?? [];
  if (parties.length === 0) return [];

  const declaredPurchasers = parties.filter((p) => isPurchaserRole(p.role));
  const declaredCount = declaredPurchasers.length;

  // Signal 1: parties flagged on_mortgage but not declared as purchasers.
  const mortgageOnlyParties = parties.filter(
    (p) => p.on_mortgage === true && !isPurchaserRole(p.role),
  );

  // Signal 2: parties with a positive contribution_amount but not declared as purchasers.
  const contributorOnlyParties = parties.filter(
    (p) =>
      typeof p.contribution_amount === 'number' &&
      p.contribution_amount > 0 &&
      !isPurchaserRole(p.role),
  );

  // Signal 3: explicit Armalytix-detected buyer count mismatch.
  const armalytixCount =
    typeof inputs.armalytixDetectedBuyerCount === 'number'
      ? inputs.armalytixDetectedBuyerCount
      : null;
  const armalytixMismatch =
    armalytixCount !== null && armalytixCount > 0 && armalytixCount !== declaredCount;

  if (
    mortgageOnlyParties.length === 0 &&
    contributorOnlyParties.length === 0 &&
    !armalytixMismatch
  ) {
    return [];
  }

  const reasons: string[] = [];
  if (mortgageOnlyParties.length > 0) {
    const names = mortgageOnlyParties
      .map((p) => p.full_name || 'unnamed party')
      .join(', ');
    reasons.push(`${mortgageOnlyParties.length} party/parties recorded as on the mortgage but not listed as purchasers (${names})`);
  }
  if (contributorOnlyParties.length > 0) {
    const names = contributorOnlyParties
      .map((p) => p.full_name || 'unnamed party')
      .join(', ');
    reasons.push(`${contributorOnlyParties.length} party/parties contributing funds but not listed as purchasers (${names})`);
  }
  if (armalytixMismatch) {
    reasons.push(`Armalytix data indicates ${armalytixCount} buyer(s) but ${declaredCount} purchaser(s) are declared on the matter file`);
  }

  // Linked ref: prefer the first non-purchaser party as anchor; fall back to first party.
  const anchor =
    mortgageOnlyParties[0] ?? contributorOnlyParties[0] ?? parties[0];

  return [{
    exceptionType: 'purchaser_count_contradiction',
    severity: 'high',
    rationale:
      `Declared purchaser list does not reconcile with the funding / mortgage signals: ${reasons.join('; ')}. ` +
      `This may indicate an undisclosed additional purchaser, beneficial owner or co-borrower.`,
    quantitativeBasis: armalytixCount !== null
      ? `Declared purchasers: ${declaredCount}; Armalytix-detected buyers: ${armalytixCount}`
      : `Declared purchasers: ${declaredCount}; non-purchaser parties with funding/mortgage signal: ${mortgageOnlyParties.length + contributorOnlyParties.length}`,
    linkedRefTable: 'case_parties',
    linkedRefId: anchor?.id ?? '',
    linkedField: 'role',
    autoGenerated: true,
    reviewerConfirmationRequired: true,
    suggestedNextAction: 'ENQUIRY: Confirm the full list of purchasers; reconcile against mortgage offer and funding contributions.',
    canTriggerEnquiry: true,
  }];
}

// ── B3 — Gift declared vs denied ─────────────────────────────────

export interface GiftDeclarationTransactionInput {
  /** Stable transaction id (sow_transactions.id) — cited in the exception payload */
  id: string;
  /** Direction; only 'incoming' transactions are considered */
  direction?: string | null;
  /** Amount (positive number); used in the rationale and quantitative basis */
  amount?: number | null;
  /** Free-text bank narrative; matched (case-insensitive, word-boundary) against gift tokens */
  description?: string | null;
  /** Transaction date (string form, free) — included verbatim in rationale where present */
  tx_date?: string | null;
  /**
   * The transaction classifier's category for this row. When equal to
   * `'gift'` (the high-confidence Armalytix-aligned signal), a single
   * hit is sufficient to emit. Token matches alone require ≥ 2.
   */
  classifiedCategory?: string | null;
}

export interface GiftDeclarationInputs {
  /**
   * Strict-boolean recording of the case form / PIF position. The rule
   * only emits when this is exactly `false`. `null` / `undefined` /
   * absence is treated as "not declared either way" and never emits —
   * absence ≠ denial.
   */
  giftDeclared: boolean | null | undefined;
  /** All transactions for the case (incoming + outgoing). The rule filters direction itself. */
  transactions: GiftDeclarationTransactionInput[];
}

/**
 * Conservative gift-narrative tokens. Word-boundary, case-insensitive.
 *
 * Excluded deliberately: bare `christmas`, bare `present` — both are
 * very noisy in real bank statement narratives.
 */
const GIFT_NARRATIVE_TOKENS: readonly string[] = [
  'gift',
  'mum',
  'mom',
  'dad',
  'mother',
  'father',
  'parents',
  'from parents',
  'birthday',
  'wedding gift',
  'xmas',
  'christmas gift',
];

/** Escape a string for safe use inside a `RegExp`. */
function escapeForRegExp(token: string): string {
  return token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Returns true when `description` contains any of the tokens with
 * word-boundary, case-insensitive matching. Multi-word tokens are
 * matched as a sequence with whitespace flexibility.
 */
function descriptionHasGiftToken(description: string | null | undefined): boolean {
  if (!description || typeof description !== 'string') return false;
  const text = description.toLowerCase();
  for (const token of GIFT_NARRATIVE_TOKENS) {
    const escaped = escapeForRegExp(token.toLowerCase()).replace(/\s+/g, '\\s+');
    const re = new RegExp(`\\b${escaped}\\b`, 'i');
    if (re.test(text)) return true;
  }
  return false;
}

export function ruleGiftDeclaredVsDenied(
  inputs?: GiftDeclarationInputs,
): ExceptionItem[] {
  // Strict-boolean precondition: only `false` triggers consideration.
  if (!inputs || inputs.giftDeclared !== false) return [];

  const txs = Array.isArray(inputs.transactions) ? inputs.transactions : [];
  if (txs.length === 0) return [];

  // Direction filter: only incoming credits can evidence a received gift.
  const incoming = txs.filter((t) => t.direction === 'incoming');
  if (incoming.length === 0) return [];

  // High-confidence Armalytix-aligned signal: classifier flagged as 'gift'.
  const classifiedGiftTxs = incoming.filter(
    (t) => t.classifiedCategory === 'gift',
  );

  // Token-narrative signal: corroboration threshold is ≥ 2 hits.
  const tokenMatchTxs = incoming.filter((t) => descriptionHasGiftToken(t.description));

  const hasClassifierSignal = classifiedGiftTxs.length >= 1;
  const hasCorroboratedTokenSignal = tokenMatchTxs.length >= 2;

  if (!hasClassifierSignal && !hasCorroboratedTokenSignal) return [];

  // De-duplicate while preserving order — a single tx can satisfy both signals.
  const citedById = new Map<string, GiftDeclarationTransactionInput>();
  for (const tx of [...classifiedGiftTxs, ...tokenMatchTxs]) {
    if (!citedById.has(tx.id)) citedById.set(tx.id, tx);
  }
  const cited = Array.from(citedById.values());

  const totalCited = cited.reduce(
    (sum, t) => sum + (typeof t.amount === 'number' ? t.amount : 0),
    0,
  );

  const reasons: string[] = [];
  if (hasClassifierSignal) {
    reasons.push(
      `${classifiedGiftTxs.length} incoming credit(s) classified as a gift by the transaction classifier`,
    );
  }
  if (hasCorroboratedTokenSignal) {
    reasons.push(
      `${tokenMatchTxs.length} incoming credit(s) whose narrative matches gift-related terms`,
    );
  }

  const anchor = cited[0];
  const exampleSnippets = cited.slice(0, 3).map((t) => {
    const amt = typeof t.amount === 'number' ? `£${t.amount.toLocaleString()}` : 'undisclosed amount';
    const date = t.tx_date ? ` on ${t.tx_date}` : '';
    const desc = t.description ? ` ("${t.description}")` : '';
    return `${amt}${date}${desc}`;
  });

  return [{
    exceptionType: 'gift_declared_vs_denied',
    severity: 'high',
    rationale:
      `The case form records that no gift has been received towards this purchase, but ` +
      `the funding evidence indicates the contrary: ${reasons.join('; ')}. ` +
      `Examples: ${exampleSnippets.join('; ')}. ` +
      `Clarification has been requested to reconcile the declared position with the funding evidence.`,
    quantitativeBasis: `Cited transactions: ${cited.length}; total of cited amounts: £${totalCited.toLocaleString()}`,
    linkedRefTable: 'sow_transactions',
    linkedRefId: anchor?.id ?? '',
    linkedField: 'classified_category',
    autoGenerated: true,
    reviewerConfirmationRequired: true,
    suggestedNextAction:
      'ENQUIRY: Confirm whether any part of the funds is a gift; if so, obtain a signed gift letter, donor bank statement, and proof of relationship.',
    canTriggerEnquiry: true,
  }];
}

// ── C5 — Employment status contradiction ─────────────────────────

export interface EmploymentStatusFundSourceInput {
  /** sow_fund_sources.id */
  id: string;
  /** Free-text source category (e.g. 'salary', 'self_employment_income', 'dividends') */
  source_category?: string | null;
  /** Declared employer name where applicable */
  employer_name?: string | null;
  /** Declared annual gross salary, if any */
  annual_gross_salary?: number | null;
}

export interface EmploymentStatusIncomeVerificationInput {
  /** sow_income_verification.id */
  id: string;
  /** Whether the bank-matched payslip name matches the client */
  payslip_name_match?: boolean | null;
  /** Whether the declared salary was found as a recurring credit on the bank data */
  salary_matched_to_bank?: boolean | null;
  /** Average monthly salary credit observed (PAYE pattern). 0/null = no PAYE pattern detected */
  avg_salary_credit?: number | null;
  /** Net pay shown on the supplied payslip, if any */
  net_pay_on_payslip?: number | null;
}

export interface EmploymentStatusInputs {
  /** All fund sources for the case (rule filters category itself) */
  fundSources: EmploymentStatusFundSourceInput[];
  /** Income verification rows from sow_income_verification (may be empty) */
  incomeVerifications: EmploymentStatusIncomeVerificationInput[];
}

/**
 * Tokens that indicate a self-employment / non-PAYE income narrative
 * declared alongside a salary source. Word-boundary, case-insensitive.
 */
const SELF_EMPLOYMENT_CATEGORY_TOKENS: readonly string[] = [
  'self employment',
  'self employed',
  'sole trader',
  'dividend',
  'dividends',
  'director',
  'company distribution',
];

function categoryHasSalary(category: string | null | undefined): boolean {
  if (!category) return false;
  return /\bsalary\b/i.test(category);
}

function categoryHasSelfEmploymentMarker(
  category: string | null | undefined,
): boolean {
  if (!category) return false;
  // Normalise: replace `_` with spaces so snake_case (e.g. `dividend_income`)
  // matches the bare token. Preserve `-` so a hyphen acts as a word boundary
  // that protects negators like `non-director`, `ex-director`, `not-director`.
  const text = category.toLowerCase().replace(/_+/g, ' ');
  for (const token of SELF_EMPLOYMENT_CATEGORY_TOKENS) {
    const normalisedToken = token.toLowerCase().replace(/[_\-]+/g, ' ');
    // Allow either whitespace or hyphen as the internal separator so
    // `self employment` matches both `self employment` and `self-employment`.
    const escaped = escapeForRegExp(normalisedToken).replace(/\s+/g, '[\\s\\-]+');
    // Negative lookbehind rejects matches immediately preceded by a negator
    // (`non`, `ex`, `not`) followed by a space or hyphen — single pass, case-insensitive.
    const pattern = new RegExp(`(?<!\\b(?:non|ex|not)[ \\-])\\b${escaped}\\b`, 'i');
    if (pattern.test(text)) return true;
  }
  return false;
}

export function ruleEmploymentStatusContradiction(
  inputs?: EmploymentStatusInputs,
): ExceptionItem[] {
  if (!inputs) return [];
  const fundSources = Array.isArray(inputs.fundSources) ? inputs.fundSources : [];
  const incomeVer = Array.isArray(inputs.incomeVerifications)
    ? inputs.incomeVerifications
    : [];

  const salarySources = fundSources.filter((fs) =>
    categoryHasSalary(fs.source_category),
  );
  if (salarySources.length === 0) return [];

  // Signal 1: a non-salary fund source on the same matter declares a self-employment marker.
  const selfEmploymentSources = fundSources.filter((fs) =>
    categoryHasSelfEmploymentMarker(fs.source_category),
  );

  // Signal 2: at least one income verification row indicates that the declared salary
  // could not be found on the bank data AND there is no observed PAYE-pattern credit.
  // Strict-boolean check on `salary_matched_to_bank === false` so absence is not denial.
  const noPayePatternEvidence = incomeVer.filter(
    (iv) =>
      iv.salary_matched_to_bank === false &&
      (typeof iv.avg_salary_credit !== 'number' || iv.avg_salary_credit <= 0),
  );

  const hasDeclaredSelfEmploymentMarker = selfEmploymentSources.length > 0;
  const hasNoPayeEvidence = noPayePatternEvidence.length > 0;

  if (!hasDeclaredSelfEmploymentMarker && !hasNoPayeEvidence) return [];

  const reasons: string[] = [];
  if (hasDeclaredSelfEmploymentMarker) {
    const cats = Array.from(
      new Set(
        selfEmploymentSources
          .map((s) => s.source_category)
          .filter((c): c is string => typeof c === 'string' && c.length > 0),
      ),
    );
    reasons.push(
      `the matter also declares non-PAYE income source(s) (${cats.join(', ')}) alongside the salary source — these typically indicate self-employment, dividend or director-distribution income`,
    );
  }
  if (hasNoPayeEvidence) {
    reasons.push(
      `${noPayePatternEvidence.length} income-verification record(s) indicate that the declared salary was not matched to a recurring PAYE-pattern credit on the bank data`,
    );
  }

  // Severity: medium when only narrative markers conflict; high when bank evidence
  // contradicts the declared PAYE position.
  const severity: 'high' | 'medium' = hasNoPayeEvidence ? 'high' : 'medium';

  // Anchor on the salary fund source so the LSAG matrix links the contradiction to
  // the declared employment record rather than an evidence-side row.
  const anchor = salarySources[0];

  return [{
    exceptionType: 'employment_status_contradiction',
    severity,
    rationale:
      `The declared employment position (salary income from ${anchor.employer_name ?? 'the stated employer'}) ` +
      `does not fully reconcile with the supporting evidence: ${reasons.join('; ')}. ` +
      `Clarification has been requested to confirm the current employment status and the basis on which the income narrative is supported.`,
    quantitativeBasis:
      typeof anchor.annual_gross_salary === 'number' && anchor.annual_gross_salary > 0
        ? `Declared annual salary: £${anchor.annual_gross_salary.toLocaleString()}`
        : null,
    linkedRefTable: 'sow_fund_sources',
    linkedRefId: anchor.id,
    linkedField: 'source_category',
    autoGenerated: true,
    reviewerConfirmationRequired: true,
    suggestedNextAction:
      'ENQUIRY: Confirm current employment status; if self-employed or director, obtain accountant\'s letter, SA302 / tax year overview, and dividend vouchers as appropriate.',
    canTriggerEnquiry: true,
  }];
}

export interface LifestyleProportionalityInputs {
  /** Total deposit (client funds) being relied upon */
  depositAmount: number;
  /** Sum of declared annual income across declared salary sources, in £ */
  statedAnnualIncome: number;
  /**
   * Plausible savings horizon in years used to compute capacity.
   * Default: 5 years (configurable).
   */
  savingsHorizonYears?: number;
  /**
   * Maximum proportion of net income realistically saved per year
   * (after living costs, tax already implicit in net). Default: 0.30.
   */
  savingsRateAssumed?: number;
  /**
   * Other evidenced wealth components that legitimately reduce the
   * gap (inheritance, sale proceeds, gifts already evidenced, prior
   * accumulated savings older than the horizon).
   */
  otherEvidencedWealth?: number;
}

export function ruleLifestyleVsIncome(
  inputs?: LifestyleProportionalityInputs,
): ExceptionItem[] {
  if (!inputs) return [];
  const {
    depositAmount,
    statedAnnualIncome,
    savingsHorizonYears = 5,
    savingsRateAssumed = 0.30,
    otherEvidencedWealth = 0,
  } = inputs;

  if (!Number.isFinite(depositAmount) || depositAmount <= 0) return [];
  if (!Number.isFinite(statedAnnualIncome) || statedAnnualIncome <= 0) return [];

  const plausibleCapacity =
    statedAnnualIncome * savingsRateAssumed * savingsHorizonYears + otherEvidencedWealth;

  if (depositAmount <= plausibleCapacity) return [];

  const gap = depositAmount - plausibleCapacity;
  const ratio = depositAmount / Math.max(plausibleCapacity, 1);

  let severity: 'critical' | 'high' | 'medium';
  if (ratio >= 3 || gap >= 100_000) severity = 'critical';
  else if (ratio >= 1.5 || gap >= 25_000) severity = 'high';
  else severity = 'medium';

  return [{
    exceptionType: 'lifestyle_inconsistent_with_income',
    severity,
    rationale:
      `Deposit of £${depositAmount.toLocaleString()} exceeds the plausible savings capacity of £${plausibleCapacity.toLocaleString()} ` +
      `derived from declared income of £${statedAnnualIncome.toLocaleString()} ` +
      `at ${(savingsRateAssumed * 100).toFixed(0)}% over ${savingsHorizonYears} years` +
      `${otherEvidencedWealth > 0 ? ` (including £${otherEvidencedWealth.toLocaleString()} of other evidenced wealth)` : ''}. ` +
      `Additional source of wealth required to close the £${gap.toLocaleString()} gap.`,
    quantitativeBasis: `Deposit £${depositAmount.toLocaleString()} vs capacity £${plausibleCapacity.toLocaleString()} (gap £${gap.toLocaleString()})`,
    linkedRefTable: 'sow_fund_sources',
    linkedRefId: '',
    linkedField: 'declared_amount',
    autoGenerated: true,
    reviewerConfirmationRequired: true,
    suggestedNextAction: 'ENQUIRY: Request explanation and evidence for the additional wealth required to support the deposit.',
    canTriggerEnquiry: true,
  }];
}

// ── A12 — Disclosure timing ──────────────────────────────────────

export type DisclosureTiming = 'upfront' | 'after_query' | 'retrospective';

export interface DisclosureTimingRecord {
  /** Topic of the disclosure (e.g. "gift from parent", "co-buyer contribution") */
  topic: string;
  /** When the explanation was actually provided */
  timing: DisclosureTiming;
  /**
   * Whether the disclosure was made only after a contradiction was
   * identified during compliance review.
   */
  triggeredByChallenge: boolean;
  /** Optional reference for traceability */
  refTable?: string;
  refId?: string;
}

export interface DisclosureTimingInputs {
  records: DisclosureTimingRecord[];
}

export function ruleLateDisclosureAfterChallenge(
  inputs?: DisclosureTimingInputs,
): ExceptionItem[] {
  if (!inputs?.records?.length) return [];

  return inputs.records
    .filter(
      (r) =>
        r.triggeredByChallenge ||
        r.timing === 'retrospective' ||
        r.timing === 'after_query',
    )
    .map<ExceptionItem>((r) => {
      const severity: 'critical' | 'high' | 'medium' | 'low' =
        r.triggeredByChallenge && r.timing === 'retrospective'
          ? 'high'
          : r.triggeredByChallenge || r.timing === 'retrospective'
          ? 'medium'
          : 'low';

      return {
        exceptionType: 'late_disclosure_after_challenge',
        severity,
        rationale:
          `Disclosure regarding "${r.topic}" was provided ${
            r.timing === 'retrospective'
              ? 'retrospectively'
              : r.timing === 'after_query'
              ? 'only after enquiry'
              : 'upfront'
          }${r.triggeredByChallenge ? ' and after a contradiction was identified during compliance review' : ''}. ` +
          `Timing of disclosure has been recorded for the file.`,
        quantitativeBasis: null,
        linkedRefTable: r.refTable ?? 'case_disclosures',
        linkedRefId: r.refId ?? '',
        linkedField: 'disclosure_timing',
        autoGenerated: true,
        reviewerConfirmationRequired: true,
        suggestedNextAction: 'NOTE: Record the timing of disclosure and consider its impact on overall reliability.',
        canTriggerEnquiry: severity !== 'low',
      };
    });
}

export function generateExceptions(inputs: ExceptionGenerationInputs): ExceptionItem[] {
  const all: ExceptionItem[] = [
    ...ruleUndeclaredIncoming(inputs.materialityAssessments, inputs.classifiedTransactions),
    ...ruleUnexplainedLargeIncoming(inputs.materialityAssessments, inputs.fundingChain.amountToProve),
    ...ruleRepeatedThirdParty(inputs.repeatedPatterns),
    ...ruleCashDeposit(inputs.classifiedTransactions),
    ...ruleReconciliationExceptions(inputs.reconciliations),
    ...ruleFundingChainExceptions(inputs.fundingChain),
    ...ruleActivityExceptions(inputs.classifiedTransactions),
    ...ruleContradictionBridge(inputs.contradictions),
    ...ruleLifestyleVsIncome(inputs.lifestyleInputs),
    ...ruleLateDisclosureAfterChallenge(inputs.disclosureTimingInputs),
    ...rulePurchaserCountContradiction(inputs.purchaserCountInputs),
    ...ruleGiftDeclaredVsDenied(inputs.giftDeclarationInputs),
    ...ruleEmploymentStatusContradiction(inputs.employmentStatusInputs),
  ];

  return deduplicateExceptions(all).sort((a, b) => {
    const sev = { critical: 0, high: 1, medium: 2, low: 3 };
    return sev[a.severity] - sev[b.severity];
  });
}

// ── Exceptions ledger (grouped for reviewer) ─────────────────────

export interface ExceptionsLedger {
  critical: ExceptionItem[];
  high: ExceptionItem[];
  medium: ExceptionItem[];
  low: ExceptionItem[];
  totalCount: number;
  enquiryTriggerable: number;
}

export function buildExceptionsLedger(exceptions: ExceptionItem[]): ExceptionsLedger {
  return {
    critical: exceptions.filter((e) => e.severity === 'critical'),
    high: exceptions.filter((e) => e.severity === 'high'),
    medium: exceptions.filter((e) => e.severity === 'medium'),
    low: exceptions.filter((e) => e.severity === 'low'),
    totalCount: exceptions.length,
    enquiryTriggerable: exceptions.filter((e) => e.canTriggerEnquiry).length,
  };
}
