/**
 * Armalytix Provenance, Verification & Extraction Types
 *
 * Core type definitions and default-rule constants for the
 * provenance / verification layer across all sow_* tables.
 */

// ── Origin: where did this value come from? ──────────────────────

export const PROVENANCE_ORIGINS = [
  'client_declaration',
  'bank_transaction_data',
  'account_summary_data',
  'uploaded_document',
  'manual_entry',
  'armalytix_generated_summary',
  'ai_inference',
  'reviewer_entry',
] as const;

export type ProvenanceOrigin = (typeof PROVENANCE_ORIGINS)[number];

// ── Verification: how well is this value supported? ──────────────

export const VERIFICATION_STATUSES = [
  'unverified',
  'declared_only',
  'evidenced_by_bank_data',
  'evidenced_by_attachment',
  'evidenced_by_multiple_sources',
  'inferred_pending_review',
  'contradicted',
  'partially_verified',
  'reviewer_confirmed',
  'reviewer_rejected',
  'not_applicable',
] as const;

export type VerificationStatus = (typeof VERIFICATION_STATUSES)[number];

// ── Extraction method ────────────────────────────────────────────

export const EXTRACTION_METHODS = [
  'exact',     // value copied verbatim from source
  'derived',   // computed from source data (e.g. average)
  'inferred',  // AI-guessed from context
  'manual',    // entered by a human
] as const;

export type ExtractionMethod = (typeof EXTRACTION_METHODS)[number];

// ── Confidence ───────────────────────────────────────────────────

export const CONFIDENCE_LABELS = ['high', 'medium', 'low'] as const;
export type ConfidenceLabel = (typeof CONFIDENCE_LABELS)[number];

// ── Contradiction types (spec section C) ─────────────────────────

export const CONTRADICTION_TYPES = [
  'unevidenced_source',
  'amount_mismatch',
  'salary_accumulation_gap',
  'missing_transaction_for_date',
  'unproven_manual_balance',
  'unevidenced_cobuyer',
  'gift_without_donor',
  'uk_mismatch',
  'undeclared_incoming',
  'mortgage_contradiction',
  'name_mismatch',
] as const;

export type ContradictionType = (typeof CONTRADICTION_TYPES)[number];

// ── Field-level provenance record ────────────────────────────────

export interface ProvenanceRecord {
  id?: string;
  case_id: string;
  armalytix_report_id?: string | null;
  ref_table: string;
  ref_id: string;
  field_name: string;
  field_value?: string | null;
  source_origin: ProvenanceOrigin;
  provenance_detail?: string | null;
  extracted_from_section?: string | null;
  extracted_from_page?: string | null;
  extraction_method: ExtractionMethod;
  confidence_score?: number | null;
  confidence_label: ConfidenceLabel;
  verification_status: VerificationStatus;
  contradiction_flag: boolean;
  missing_evidence_flag: boolean;
  reviewer_locked: boolean;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
}

// ── Contradiction result (returned by detector functions) ────────

export interface ContradictionResult {
  type: ContradictionType;
  summary: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  affectedRefTable: string;
  affectedRefId: string;
  affectedField?: string;
  autoGenerated: boolean;
}

// ── Default provenance rules per data-type (spec section E) ──────

export interface DefaultProvenanceRule {
  source_origin: ProvenanceOrigin;
  verification_status: VerificationStatus;
  confidence_label: ConfidenceLabel;
  extraction_method: ExtractionMethod;
  note: string;
}

/**
 * Rule 1 – Client questionnaire answers in the Armalytix report.
 * NEVER treated as verified fact simply because they appear in the report.
 */
export const DEFAULT_CLIENT_DECLARATION: DefaultProvenanceRule = {
  source_origin: 'client_declaration',
  verification_status: 'declared_only',
  confidence_label: 'low',
  extraction_method: 'exact',
  note: 'Client-provided answer; requires independent verification.',
};

/**
 * Rule 2 – Connected account balance & transaction data (Open Banking).
 */
export const DEFAULT_BANK_DATA: DefaultProvenanceRule = {
  source_origin: 'bank_transaction_data',
  verification_status: 'evidenced_by_bank_data',
  confidence_label: 'high',
  extraction_method: 'exact',
  note: 'Sourced directly from Open Banking feed.',
};

export const DEFAULT_ACCOUNT_SUMMARY: DefaultProvenanceRule = {
  source_origin: 'account_summary_data',
  verification_status: 'evidenced_by_bank_data',
  confidence_label: 'high',
  extraction_method: 'derived',
  note: 'Derived from Open Banking account summary.',
};

/**
 * Rule 3 – Uploaded supporting files referenced in the report.
 * Only verified AFTER the linked file actually exists.
 */
export const DEFAULT_UPLOADED_DOCUMENT: DefaultProvenanceRule = {
  source_origin: 'uploaded_document',
  verification_status: 'unverified', // upgraded to evidenced_by_attachment once file confirmed
  confidence_label: 'medium',
  extraction_method: 'exact',
  note: 'Referenced uploaded attachment; verification depends on linked file presence.',
};

/**
 * Rule 4 – Manual balances entered by the client.
 */
export const DEFAULT_MANUAL_ENTRY: DefaultProvenanceRule = {
  source_origin: 'manual_entry',
  verification_status: 'unverified',
  confidence_label: 'low',
  extraction_method: 'manual',
  note: 'Manually entered value; no independent evidence unless linked.',
};

/**
 * Rule 5 – AI-derived links / inferences.
 */
export const DEFAULT_AI_INFERENCE: DefaultProvenanceRule = {
  source_origin: 'ai_inference',
  verification_status: 'inferred_pending_review',
  confidence_label: 'medium',
  extraction_method: 'inferred',
  note: 'AI-generated linkage or inference; requires reviewer confirmation.',
};

/**
 * Armalytix-generated summary values (e.g. "amount to prove", "excess/shortfall").
 */
export const DEFAULT_ARMALYTIX_SUMMARY: DefaultProvenanceRule = {
  source_origin: 'armalytix_generated_summary',
  verification_status: 'declared_only',
  confidence_label: 'medium',
  extraction_method: 'derived',
  note: 'Calculated by Armalytix from client declarations + bank data; treat as advisory.',
};

/**
 * Reviewer-entered values.
 */
export const DEFAULT_REVIEWER_ENTRY: DefaultProvenanceRule = {
  source_origin: 'reviewer_entry',
  verification_status: 'reviewer_confirmed',
  confidence_label: 'high',
  extraction_method: 'manual',
  note: 'Entered or confirmed by authorised reviewer.',
};

/** Material fields that support field-level provenance tracking. */
export const MATERIAL_FIELDS = [
  'declared_amount',
  'source_category',
  'employer_name',
  'date_received',
  'contribution_amount',
  'counted_toward_proof',
  'net_pay_on_payslip',
  'current_balance',
  'purchase_price',
  'mortgage_amount',
  'amount_to_prove',
  'excess_shortfall',
  'annual_gross_salary',
] as const;

export type MaterialField = (typeof MATERIAL_FIELDS)[number];
